### PR TITLE
First draft of new Moving Pictures tutorial docs

### PR DESCRIPTION
**Pull request by mestaki**
This is the first draft of the new tutorial using Moving Pictures data. It is meant to replace the existing README as it includes installation and env set up.

### CODE REVIEW

**Comment by emperor-helper** [comment]
The following artifacts were built for this PR: [artifact 1](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F290%2Fempire-biplot.qzv)

**Comment by emperor-helper** [comment]
The following artifacts were built for this PR: [artifact 1](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F290%2Fempire-biplot.qzv)

**Comment by emperor-helper** [comment]
The following artifacts were built for this PR: [artifact 1](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F290%2Fempire-biplot.qzv)

**Comment by ElDeveloper** [comment]
Thanks so much @mestaki!!! 🎉  And congrats on your first PR to Empress!

**Comment by emperor-helper** [comment]
The following artifacts were built for this PR: [artifact 1](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F290%2Fempire.qzv), [artifact 2](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F290%2Fempire-biplot.qzv), [artifact 3](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F290%2Fempress-tree.qzv)

**Comment by emperor-helper** [comment]
The following artifacts were built for this PR: [empire-biplot.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F290%2Fempire-biplot.qzv), [empire.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F290%2Fempire.qzv), [empress-tree.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F290%2Fempress-tree.qzv)

**Pull request merged**
