### PR TITLE
PERF: Improve remove_empty performance

### PR DESCRIPTION
**Pull request by ElDeveloper**
Equivalent to: https://github.com/biocore/biom-format/pull/847

### CODE REVIEW

**Comment by emperor-helper** [comment]
The following artifacts were built for this PR: [empire-biplot.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F328%2Fempire-biplot.qzv), [empire.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F328%2Fempire.qzv), [empress-tree.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fmchelper.ucsd.edu%2Fdownloads%2Fempress%2F328%2Fempress-tree.qzv)

**Comment by ElDeveloper** [comment]
@wasade this mostly mimics the PR submitted to BIOM last week, would be great if  you can approve/merge.

**Comment by ElDeveloper** [comment]
Thanks @wasade!

**Comment by ElDeveloper** [comment]
Thanks @fedarko!

**Pull request merged**
